services:
  - type: web
    name: ee-exam-app
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NOTION_TOKEN
        sync: false
      - key: NOTION_DB_CHAPTERS
        value: d2dd115dbf384750b138e20c39d2e2fe
      - key: NOTION_DB_WRONG
        value: 138e5f939f79405d9b072fc61900e920
      - key: APP_KEY
        sync: false
      - key: NOTION_HOME_URL
        sync: false
